### ISSUE TITLE
Missing trailing slash in collection urls prevents deletion of folders

### ISSUE THREAD

**Issue by micw** [arut/nginx-dav-ext-module#20]
According to the RFC http://www.webdav.org/specs/rfc4918.html#collections.of.web.resources URLs to collections (=folders) SHOULD have a traling slash.

This NGINX module does not append the slash to collection URIs, e.g. when using PROPFIND to list a folder's content.

As a result, common clients like GVFS or Windows fail to delete folders because of a missing trailing slash. There's a check for this slash in nginx's webdav module: https://trac.nginx.org/nginx/browser/nginx/src/http/modules/ngx_http_dav_module.c#L344

Solution: Add a trailing slash on href for folders.

**Comment by renyidong** [comment]
Apologies if I'm the disturbing newbie.

I‘m trying to work on this issue. Seems it can be fixed by some code around [ngx_http_dav_ext_module.6:620](../blob/master/ngx_http_dav_ext_module.c#L620). Simply check `de->d_type` and append the slash should do the work. 

I'm confused at [line 620](../blob/master/ngx_http_dav_ext_module.c#L620)
```
uc = ngx_palloc(r->pool, len + 2 * ngx_escape_uri(NULL,
			(u_char *) de->d_name, len, NGX_ESCAPE_URI_COMPONENT));
```
Seems we are allocating memory for the escaped uri component of directory name. ngx_escape_uri() should return the escaped length here. The following call of ngx_escape_uri() fills the allocated string. So simply allocate escaped length should be enough.

Could anyone explain why we need to allocate (original length + 2 * escaped length) ?

**Comment by arut** [comment]
This is addressed in the [v2](https://github.com/arut/nginx-dav-ext-module/tree/v2) branch and will eventually become  a new release.

**Comment by arut** [comment]
[v2.0.0](https://github.com/arut/nginx-dav-ext-module/tree/v2.0.0)
